void bubble(int *vet,int n);
void selection(int *vet,int n);
void reset_vet(int *vet,int n);
void insertion(int *vet,int n);
void mergesort(int *vet,int ini, int fim, int n);
void merge(int *vet,int ini, int meio, int fim);
void maxHeap(int *vet,int n,int i);
void build_maxHeap(int *vet,int n);
void heapsort(int *vet,int n);
void quicksort(int *vet,int ini, int fim,int n);
void countingsort (int *vet,int n);